export const Colors = {
  screenBgColor: "#01575c",
  cardBgColor: "#ffffff",
  tabBgColor: "#e1e1e2",
  groupBgColor: "#dcefea",
  gradientStart: "#ffffff",
  gradientEnd: "#cbdada",
  tabIconColor: "#01575c",
  toggleBgColor: "#001b2c",
  toggleColor: "#ffffff",
  returnButtonBgColor: "#348085",
  headerTitleColor: "#ffffff",
  dangerTextColor: "#ef4444",
  inputLabelColor: "#ffffff",
  confirmBtnBg: "#01575c",
  confirmBtnText: "#ffffff",
  cancelBtnBg: "#a3a3a3",
  cancelBtnText: "#fefefe",
  likeIconColor: "#FF6B6B",
  shallowTextColor: "#ffffff",
  focusText: "#ffffff",
  logOutButtonBg: "#ffffff",
  profileText: "#ffffff",
  modalTitle: "#12162e",
  addFocusButton: "#ffffff",
  addFocusMedalLabel: "#707f89",
  deleteButton: "#576f70",

  // undefined
  lighterThanBg: "#8fb5b7",
  labelText: "#707f89",
  greyIconColor: "#576f70",
  colorYellow: "#ffe6c6",
};
